-- ============================================================
-- AI NATIVES FULL SUPABASE SCHEMA
-- Real-time Supabase backend with JWT auth, CV matching and storage.
-- WARNING: This resets all AI Natives tables and deletes old test data.
-- ============================================================

drop table if exists public.data_removal_requests cascade;
drop table if exists public.user_settings cascade;
drop table if exists public.applications cascade;
drop table if exists public.jobs cascade;
drop table if exists public.profiles cascade;
drop table if exists public.users cascade;

create table public.users (
  id bigint generated by default as identity primary key,
  full_name text not null,
  email text not null unique,
  password_hash text not null,
  role text not null default 'user',
  phone text,
  status text not null default 'Active',
  accessibility_needs text,
  created_at timestamptz not null default now(),
  constraint users_role_check check (role in ('user', 'employer', 'admin')),
  constraint users_status_check check (status in ('Active', 'Suspended', 'Inactive'))
);

create table public.profiles (
  id bigint generated by default as identity primary key,
  user_id bigint not null unique references public.users(id) on delete cascade,
  bio text,
  skills text,
  education text,
  experience text,
  cv_file_path text,
  cv_text text,
  profile_picture_path text,
  accessibility_preferences text,
  updated_at timestamptz not null default now()
);

create table public.jobs (
  id bigint generated by default as identity primary key,
  employer_id bigint references public.users(id) on delete set null,
  title text not null,
  company_name text not null,
  location text,
  job_type text,
  work_mode text,
  department text,
  salary text,
  experience_level text,
  closing_date date,
  contact_email text,
  description text,
  requirements text,
  benefits text,
  status text not null default 'Active',
  created_at timestamptz not null default now(),
  constraint jobs_status_check check (status in ('Active', 'Closed', 'Suspended', 'Draft'))
);

create table public.applications (
  id bigint generated by default as identity primary key,
  user_id bigint not null references public.users(id) on delete cascade,
  job_id bigint not null references public.jobs(id) on delete cascade,
  cv_file_path text,
  cv_text text,
  document_file_path text,
  cover_note text,
  status text not null default 'Pending',
  comment text,
  created_at timestamptz not null default now(),
  constraint applications_status_check check (status in ('Pending','Reviewed','Shortlisted','Interview','Rejected','Accepted')),
  constraint applications_unique_user_job unique(user_id, job_id)
);

create table public.user_settings (
  id bigint generated by default as identity primary key,
  user_id bigint not null unique references public.users(id) on delete cascade,
  settings_json jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now()
);

create table public.data_removal_requests (
  id bigint generated by default as identity primary key,
  user_id bigint not null references public.users(id) on delete cascade,
  reason text,
  status text not null default 'Pending',
  created_at timestamptz not null default now(),
  constraint data_removal_status_check check (status in ('Pending', 'Approved', 'Rejected', 'Completed'))
);

insert into storage.buckets (id, name, public)
values ('ai-natives-files', 'ai-natives-files', false)
on conflict (id) do nothing;

create index if not exists idx_users_role on public.users(role);
create index if not exists idx_users_email on public.users(email);
create index if not exists idx_users_status on public.users(status);
create index if not exists idx_jobs_employer on public.jobs(employer_id);
create index if not exists idx_jobs_status on public.jobs(status);
create index if not exists idx_jobs_closing_date on public.jobs(closing_date);
create index if not exists idx_applications_user on public.applications(user_id);
create index if not exists idx_applications_job on public.applications(job_id);
create index if not exists idx_applications_status on public.applications(status);

-- Default admin account.
-- Email: ainatives09@gmail.com
-- Password: @AI NATIVES 05
insert into public.users (full_name, email, password_hash, role, status)
values ('AI Natives', 'ainatives09@gmail.com', '$2a$10$PlaceHolder', 'admin', 'Active')
on conflict (email) do update set
  full_name = excluded.full_name,
  password_hash = excluded.password_hash,
  role = 'admin',
  status = 'Active';

insert into public.profiles (user_id)
select id from public.users where email = 'ainatives09@gmail.com'
on conflict (user_id) do nothing;
